version: '3'

services:
  rabbitmq:
      image: rabbitmq:3-management
      networks:
        - ex2network

  service1:
    build:
      context: ./service1
    networks:
      - ex2network

  service2:
    build:
      context: ./service2
    networks:
      - ex2network

  monitor:
    build:
      context: ./monitor
    ports:
      - "8087:8087"
    networks:
      - ex2network

networks:
  ex2network: