version: '3'
services:
  service1:
    build:
      context: ./service1
    depends_on:
      - service2
    volumes:
      - ./logs:/logs
  service2:
    build:
      context: ./service2
    volumes:
      - ./logs:/logs